// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVbMbzPC2IDN0GidecnPk0vQkA0IioB0',
    appId: '1:947241490493:web:c29da4bfda67bfa6abb254',
    messagingSenderId: '947241490493',
    projectId: 'tugasbesarp',
    authDomain: 'tugasbesarp.firebaseapp.com',
    storageBucket: 'tugasbesarp.appspot.com',
    measurementId: 'G-Q2E5QN00TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzkv0oHIz_22XbuU3NQXDEEopNU8nd998',
    appId: '1:947241490493:android:b1cdb7e435297805abb254',
    messagingSenderId: '947241490493',
    projectId: 'tugasbesarp',
    storageBucket: 'tugasbesarp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOvzgqc5_W_Xps5CGZFfRJG0Pbh_MCiAI',
    appId: '1:947241490493:ios:d457e3f106c30896abb254',
    messagingSenderId: '947241490493',
    projectId: 'tugasbesarp',
    storageBucket: 'tugasbesarp.appspot.com',
    iosBundleId: 'com.example.tbp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOvzgqc5_W_Xps5CGZFfRJG0Pbh_MCiAI',
    appId: '1:947241490493:ios:b677a271bfcf2272abb254',
    messagingSenderId: '947241490493',
    projectId: 'tugasbesarp',
    storageBucket: 'tugasbesarp.appspot.com',
    iosBundleId: 'com.example.tbp.RunnerTests',
  );
}
